server:
  port: 9002

spring:
  application:
    name: COURSE-SERVICE
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

exceptions:
  itemnotfound:
    message: Course with id %d not found
  studentalreadyenrolled:
    message: Student with id %d already enrolled in course with id %d